### ISSUE TITLE
Register API Key 404

### ISSUE THREAD

**Issue by drakgoku** [manticorp/Nextzen16bitGrayscaleHeightmap#4]
Wrong link attach in 

Current link.
"https://developers.nextzen.org/](https://github.com/manticorp/Nextzen16bitGrayscaleHeightmap/blob/main/a". 
Fix it.
"https://developers.nextzen.org/](..https://developers.nextzen.org/).

**Comment by manticorp** [comment]
Fixed the link with commit 774e716a96e1a574ed12429dd186a7db9a5b4926
