### ISSUE TITLE
Composer Version.

### ISSUE THREAD

**Issue by drakgoku** [manticorp/Nextzen16bitGrayscaleHeightmap#5]
To install composer for the correct versions.

 "require": {
        "guzzlehttp/guzzle": "^7.0",

To
 "require": {
        "guzzlehttp/guzzle": "^7.0||8.0||8.2.2", 

Or the version of PHP you have

**Comment by manticorp** [comment]
This is the version of the guzzle library, available on packagist:

[https://packagist.org/packages/guzzlehttp/guzzle](https://packagist.org/packages/guzzlehttp/guzzle)

It is currently (at time of writing) on version 7.5.0.

The number here does not reference the PHP version.

guzzle 7.0 (the version required in composer) has a minimum requirement of php version ^7.2.5:

[https://packagist.org/packages/guzzlehttp/guzzle#7.0.0](https://packagist.org/packages/guzzlehttp/guzzle#7.0.0)

![image](https://user-images.githubusercontent.com/3750419/218407608-497864ad-d22f-4390-994b-d82dc99fa57d.png)

**Comment by drakgoku** [comment]
I was mentioning this as a help.

If you have version 8.2.2 of PHP com Yo and you run composer install it will give you an error of the types require 'vendor/autoload.php';.

So what you have to do is select the version manually. Here is a post that tells you.

https://stackoverflow.com/questions/41209349/requirevendor-autoload-php-failed-to-open-stream

I am mentioning it, because your tool gave me that problem and it may give many people the same error, for that reason I have commented on it.

But if you don't want to leave the publication open, warn in the notes of what I told you.

**Comment by manticorp** [comment]
What's the exact error you're getting?
I might be able to help better that way.

**Comment by drakgoku** [comment]
I may have explained it wrong.

It gave me a version error, because in your autoload.php you only have version "^7.0" configured.
So if you are running 8.2.2 like I am you have to change it to "guzzlehttp/guzzle": "8.2.2". If you don't put this it will give an error and to merge both versions 7, 8 and 8.2.2 just type "guzzlehttp/guzzle": "^7.0||8.0||8.2.2".

This will happen more times to users who don't know about it. Therefore, I wrote it in case of having an error when installing the composer.

**Comment by yezzer** [comment]
> "guzzlehttp/guzzle": "^7.0||8.0||8.2.2",

Thanks! I was having this issue too, that resolved it.

**Comment by manticorp** [comment]
@drakgoku @yezzer

I have created a version of this that runs in-browser, you can find it here:

https://manticorp.github.io/unrealheightmap/

Let me know how you get on! Should be a lot easier than running it from the command line.

**Comment by drakgoku** [comment]
I answered you on the other side.
Anyway, it's pretty good. Some "spikes" but otherwise pretty good.

For the issue of reducing peaks, I have read that you have to use terrain generation software, since not all the information arrives with the conversion.
But for now, it's fine.

I'll see if there are improvements or progress over time.
Thank you so much.

**Comment by manticorp** [comment]
@drakgoku Thank you for saying!

If there are any problems with the data, I think they can be submitted here:

[https://github.com/tilezen/joerd/issues](https://github.com/tilezen/joerd/issues)

More information here:

[https://www.mapzen.com/blog/elevation/](https://www.mapzen.com/blog/elevation/)
