### ISSUE TITLE
Change the access method

### ISSUE THREAD

**Issue by drakgoku** [manticorp/Nextzen16bitGrayscaleHeightmap#6]
On the page https://developers.nextzen.org/ can you change the access method?

I don't trust small APIS to link my Github account.

**Comment by manticorp** [comment]
I am in no way affiliated with nextzen.

**Comment by drakgoku** [comment]
It is one thing to be an affiliate and the other is for nextzen to enable another access route.

I don't trust small APIS. call me weird But I'm right. I do not know how reliable and how reliable it is.
I hardly trust Google enough to trust Cocacola... Imagine yourself in hardware stores Paco...

**Comment by manticorp** [comment]
That's fair I understand, I just don't have any control of this unfortunately!
